update machines

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -127,6 +127,13 @@ jobs:
           set -e
           export FLYCTL_INSTALL="/home/runner/.fly"
           export PATH="$FLYCTL_INSTALL/bin:$PATH"
+          
+          MACHINE_ID=$(flyctl machines list --json | jq -r '.[0].id')
+
+	  if [ -z "$MACHINE_ID" ] || [ "$MACHINE_ID" = "null" ]; then
+	    echo "❌ ERROR: Tidak ada Machine ID yang ditemukan! Pastikan aplikasi telah berjalan sebelumnya."
+	    exit 1
+	  fi
 
           if [ -z "$FLY_APP_NAME" ]; then
             echo "❌ ERROR: FLY_APP_NAME tidak ditemukan. Pastikan sudah diatur di GitHub Secrets!"
@@ -135,7 +142,10 @@ jobs:
 
           echo "🚀 Deploying to Fly.io..."
           flyctl deploy --remote-only --strategy immediate --regions sin -a "$FLY_APP_NAME" --build-only
-          flyctl machines update --app "$FLY_APP_NAME" --image "registry.fly.io/$FLY_APP_NAME:latest"
+          
+          echo "🔄 Updating Machine ID: $MACHINE_ID"
+	  flyctl machines update "$MACHINE_ID" --app "$FLY_APP_NAME" --image "registry.fly.io/$FLY_APP_NAME:latest"
+          #flyctl machines update --app "$FLY_APP_NAME" --image "registry.fly.io/$FLY_APP_NAME:latest"
 
       - name: Restart Fly.io App
         run: |
